# Generated by Django 3.1.4 on 2020-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReListing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
                ('heating', models.TextField(blank=True, null=True)),
                ('hometype', models.TextField(blank=True, db_column='homeType', null=True)),
                ('numbathrooms', models.FloatField(blank=True, db_column='numBathrooms', null=True)),
                ('numbedrooms', models.FloatField(blank=True, db_column='numBedrooms', null=True)),
                ('parking', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pricepersqm', models.FloatField(blank=True, db_column='pricePerSqm', null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('livingrooms', models.FloatField(blank=True, db_column='LivingRooms', null=True)),
                ('kitchens', models.FloatField(blank=True, db_column='Kitchens', null=True)),
                ('wc', models.FloatField(blank=True, db_column='WC', null=True)),
                ('orientation', models.TextField(blank=True, db_column='Orientation', null=True)),
                ('newlybuilt', models.FloatField(blank=True, db_column='NewlyBuilt', null=True)),
                ('storage', models.FloatField(blank=True, db_column='Storage', null=True)),
                ('views', models.FloatField(blank=True, db_column='Views', null=True)),
                ('rooftop', models.FloatField(blank=True, db_column='RoofTop', null=True)),
                ('swimmingpool', models.FloatField(blank=True, db_column='SwimmingPool', null=True)),
                ('roadfront', models.FloatField(blank=True, db_column='RoadFront', null=True)),
                ('corner', models.FloatField(blank=True, db_column='Corner', null=True)),
                ('renovated', models.FloatField(blank=True, db_column='Renovated', null=True)),
                ('yearrenovated', models.FloatField(blank=True, db_column='YearRenovated', null=True)),
                ('needsrenovation', models.FloatField(blank=True, db_column='NeedsRenovation', null=True)),
                ('listedbuilding', models.FloatField(blank=True, db_column='ListedBuilding', null=True)),
                ('neoclassico', models.FloatField(blank=True, db_column='Neoclassico', null=True)),
                ('unfinished', models.FloatField(blank=True, db_column='Unfinished', null=True)),
                ('professionaluse', models.FloatField(blank=True, db_column='ProfessionalUse', null=True)),
                ('distancefromsea', models.FloatField(blank=True, db_column='DistanceFromSea', null=True)),
                ('energycat', models.TextField(blank=True, db_column='EnergyCat', null=True)),
                ('luxury', models.FloatField(blank=True, db_column='Luxury', null=True)),
                ('studentaccomodation', models.FloatField(blank=True, db_column='StudentAccomodation', null=True)),
                ('summerhouse', models.FloatField(blank=True, db_column='SummerHouse', null=True)),
                ('buildingzone', models.TextField(blank=True, db_column='BuildingZone', null=True)),
                ('category', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('numwcbath', models.FloatField(blank=True, db_column='numWCBath', null=True)),
                ('numrooms', models.FloatField(blank=True, db_column='numRooms', null=True)),
                ('areaperroom', models.FloatField(blank=True, db_column='areaPerRoom', null=True)),
                ('areaperwcbath', models.FloatField(blank=True, db_column='areaPerWCBath', null=True)),
                ('posfeatures', models.FloatField(blank=True, db_column='posFeatures', null=True)),
                ('negfeatures', models.FloatField(blank=True, db_column='negFeatures', null=True)),
                ('price_p', models.FloatField(blank=True, db_column='price_P', null=True)),
                ('price_stderr', models.FloatField(blank=True, db_column='price_StdErr', null=True)),
                ('pricepersqm_p', models.FloatField(blank=True, db_column='pricePerSqm_P', null=True)),
                ('pricepersqm_stderr', models.FloatField(blank=True, db_column='pricePerSqm_StdErr', null=True)),
            ],
            options={
                'db_table': 'RE_Listing',
                'managed': False,
            },
        ),
    ]
